import type { Metadata } from "next";
import "../styles/globals.css";
import Navbar from "@/components/Navbar";
import SidebarLeft from "@/components/SidebarLeft";
import SidebarRight from "@/components/SidebarRight";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#edf2f6]">
        <Navbar />
        <SidebarLeft />
        <SidebarRight />
        <div className="flex justify-center pt-[110px]">
          <div className="max-w-[1250px]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
